# Generated by Django 5.1 on 2024-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='help_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/tasks/'),
        ),
    ]
